BEGIN;
DELETE FROM config WHERE key IN (
  'LLM_TIER_SPLIT_ENABLED', 'LLM_MODEL_REGIME', 'LLM_MODEL_RANKING',
  'LLM_MODEL_VETO', 'LLM_MODEL_STOP_ADJUST', 'LLM_MODEL_EXIT_VETO',
  'LLM_MODEL_NEWS'
);
DROP TABLE IF EXISTS llm_calls;
COMMIT;
